# Header
menu:
  首页: /
  存档: /archives
  关于: /about
  ToDo: /todolist

# Content
excerpt_link: 阅读全文 #替换为中文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#SNS分享，身在天朝，当然用“百度分享”，暂时默认，后面会介绍
addthis: 

#google_analytics: #要使用google_analytics进行统计的话，这里需要配置ID，暂时默认，后面介绍
rss:  #生成RSS，需要配置路径，暂时默认，后面介绍